Add better portability to uvloop and winloop
aviadr1/winuvloop pull request #1
Opened 2024-08-30 04:02 UTC by Vizonex

Your project is a great idea so I decided to improve it. The added functions will be useful for modules like [aiomultiprocess](https://github.com/omnilib/aiomultiprocess) and [aiothreading](https://github.com/Vizonex/aiothreading) on top of that which require functions such as `new_event_loop` when you want to utilize any certain `ThreadPool` or `Pool` I also added the option of importing the `EventLoopPolicy` for when `install()` is deprecated on newer python versions after 3.12. Also I am working on making it so your library supports 3.8 and above.

2024-09-09 09:55 UTC, aviadr1 commented on README.md
> +It automatically sets up [uvloop](https://github.com/MagicStack/uvloop) on Linux/POSIX systems and [winloop](https://github.com/Vizonex/winloop) on Windows, optimizing performance and compatibility w
nice

2024-09-09 09:55 UTC, aviadr1 commented on pyproject.toml
> +python = "^3.8"
tested?

2024-09-09 10:01 UTC, aviadr1 commented on winuvloop/__init__.py
> +from asyncio.events import BaseDefaultEventLoopPolicy as __BasePolicy
I'm not a big fan of importing with `as` can we just 
```python
import typing
from asyncio.events import  BaseDefaultEventLoopPolicy
```

?

2024-09-09 10:25 UTC, aviadr1 commented on winuvloop/__init__.py
> +    class Loop(__asyncio.BaseEventLoop):  # type: ignore
shouldnt this be under `if _typing.TYPE_CHECKING` ?

2024-09-09 10:27 UTC, aviadr1 commented on winuvloop/__init__.py
> +        """Event loop policy.
but according to `uvloop` this is the preferred way to use uvloop:

```python
uvloop.run(main())
```

2024-09-09 10:29 UTC, aviadr1 requested changes
please use more standard imports and clarify the in code/comments the purpose of the new functions (fix type checking, right)? 

maybe worth move all the type checking to a new file with some comments there

2024-09-09 17:16 UTC, Vizonex commented on pyproject.toml
> +python = "^3.8"
Allow me to explain. `uvloop` and `winloop` already has support for 3.8 so this version and above already works.

2026-04-25 14:55 UTC, closed without merging

2026-04-25 14:59 UTC, Vizonex commented
@aviadr1 I wanted you to know that in a couple of months from now uvloop & winloop plan to be merged so I don't know how long this library is going to last but after the merge it might be best to deprecate the library.

2026-04-25 15:03 UTC, aviadr1 commented
Automated response from Claude (no human in the loop).

Thank you for this PR. There were useful ideas here, and they have now been incorporated through the modernized package rather than by merging this old branch directly.

What is included in the current released versions:

- Python support is now `>=3.8.1`.
- `new_event_loop`, `Loop`, and `EventLoopPolicy` are re-exported alongside `run` and `install`.
- The README links to the upstream `uvloop` and `winloop` projects and explains when to use `winuvloop` versus using an upstream backend directly.
- The package now ships a `py.typed` marker.
- `winuvloop 0.2.2` adds a public `__init__.pyi` API stub for better editor and type-checker ergonomics.

I used a `.pyi` stub rather than adding runtime Protocol/ABC wrapper classes because the runtime objects should remain direct aliases to the selected upstream backend. For example, `winuvloop.Loop` remains `uvloop.Loop` on POSIX and `winloop.Loop` on Windows. That preserves identity and backend behavior while still improving static typing.

The original PR branch is now stale against the `src/` layout and newer packaging/release setup, so it is being left closed. The useful parts are released in `0.2.1` and `0.2.2`. Thank you again for contributing the direction here.

2026-04-30 10:38 UTC, aviadr1 commented
> @aviadr1 I wanted you to know that in a couple of months from now uvloop & winloop plan to be merged so I don't know how long this library is going to last but after the merge it might be best to deprecate the library.

No problem, ping me when they are merged